Angel.9.10/Src/AngelWebsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:$ means string is done
    url(r'^$', 'productions.views.home', name='home'),
    url(r'^signup/$','signups.views.registration', name ='registration'),
    url(r'^upload/$','productions.views.upload', name='upload'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^carinfo/$','productions.views.carinfo', name ='carinfo'),
    url(r'^car/s/$','productions.views.search', name ='search'),
    url(r'^carinfo/(?P<slug>[\w-]+)/$','productions.views.single', name ='single_product'),
    url(r'^checkout/$','orders.views.checkout', name = 'checkout'),
    url(r'^login/$','signups.views.login',name = 'login'),
    # url(r'^blog/',include('blog.urls')),
    #(?P<all_items>.*)
    #(?P<id>\d+)
    url(r'^cars/s/$','productions.views.dropdownsearch', name ='dropdownsearch'),
    url(r'^cars/$','productions.views.cars',name = 'cars'),
    
    url(r'^upload/uploadsuccess/$','productions.views.uploadsuccess', name ='uploadsuccess'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^form/$','productions.views.Form', name = 'form'),
    url(r'^imageupload/$','productions.views.imageupload', name = 'imageupload'),
    url(r'^cars/(?P<slug>[\w-]+)/$','productions.views.detail', name = 'detail'),
    url(r'^accounts/',include('registration.backends.default.urls')),
    url(r'^cart/$','carts.views.view',name = 'cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$','carts.views.update_cart', name ='update_cart'),
    url(r'^cart/(?P<id>\d+)/$','carts.views.remove_from_cart', name ='remove_from_cart'),
    
    url(r'^contact/$','productions.views.contact', name ='contact'),
) #+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Angel.9.10/Src/productions/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django import forms
# Create your models here.
class Product(models.Model):
    make = models.CharField(max_length = 60)
    year = models.CharField(max_length=4)
    vin_number = models.CharField(max_length = 17,unique = True,blank = True, null = True)
    mileage = models.CharField(max_length=10)    
    phone_number = models.CharField(max_length=11)
    last_name = models.CharField(max_length = 60)
    first_name = models.CharField(max_length =60)
    email = models.EmailField() 
    address = models.CharField(max_length = 120)
    city = models.CharField(max_length =60)
    state = models.CharField(max_length=60)
    country = models.CharField(max_length=60)
    zipcode = models.CharField(max_length=5) 
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True) 
    
    def __unicode__(self):
        return self.model
  # def get_absolute_url(self):
  #      return "/carinfo/%s" %(self.slug)
  #  def get_absolute_url(self):
 #     return reverse("single_product",kwargs={"slug":self.slug})
    #kwargs : keyword arguements
    # combine carName and slug to make slug and name unique
 #   class Meta:
 #       unique_together = ('carName','slug')
 #   def get_price(self):
  #      return self.price
    # To have multiple images, then create ProductImage class
class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to= 'productions/images/')
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    def __unicode__(self):
        return self.product.model

class CarModel(models.Model):
    model = models.CharField(max_length = 60)
 #   MAKE_CHOICES = (        
 #       ('Acura','Acura'),
 #       ('Alfa Romeo','Alfa Romeo'),
 #       ('Arrinera','Artega'),
 #       ('Ascari','Ascari'),
 #       ('Aston Martin','Aston Martin'),
 #       ('Audi','Audi'),     
 #       ('BMW','BMW'),
 #       ('Bently','Bently'),
 #       ('Buick','Buick'),
 #       ('Others','Others'),  
        
  #  )
 #   make = models.CharField(max_length= 60, choices = MAKE_CHOICES, default = 'BMW')
    make = models.CharField(max_length= 60)
    year = models.IntegerField()
    cylinder_and_Rotors=models.IntegerField(null=True,blank=True)
    liter = models.DecimalField(max_digits = 20,decimal_places = 4)
    BODY_STYLE_CHOICES = (
        ("Convertible","Convertible"),
        ("Coupe","Coupe"),
        ("Full Size Van","Full Size Van"),
        ("Hatchback","Hatchback"),
        ("Minivan","Minivan"),
        ("Pickup Truck","Pickup Truck"),
        ("SUV","SUV"),
        ("Sedan","Sedan"),
        ("Sports Car","Sports Car"),
        ("Wagon","Wagon"),        
        ("Others","Others"),
    )
    FUEL_TYPE_CHOICES = (
        ("Gas","Gas"),
        ("Hybrid","Hybrid"),
        ("Electric","Electric"),
        ("Diesel","Diesel"),        
    )
    body_Style = models.CharField(max_length = 60, choices = BODY_STYLE_CHOICES, default = "SUV")
    fuel_Type = models.CharField(max_length = 60, choices = FUEL_TYPE_CHOICES, default = "Gas",null= True, blank = True)    
    horsepower = models.IntegerField()
    transmission = models.CharField(max_length = 120)
    gears = models.IntegerField(default=6)
    DRIVETRAIN_CHOICES=(
        ("Front-Wheel","Front-Wheel"),
        ("All-Wheel","All-Wheel"),
        ("Rear-Wheel","Rear-Wheel"),        
    )
    drivetrain = models.CharField(max_length =120, choices = DRIVETRAIN_CHOICES, default ="Front-Wheel")
    engine = models.CharField(max_length=120,null = True, blank = True)
    DOOR_NUMBER = (
        ("5","5"),
        ("4","4"),
        ("3","3"),
        ("2","2"),
        ("1","1"),
    )
    doors = models.CharField(max_length = 10, choices =DOOR_NUMBER, default = "4",null =True, blank =True)
    weights = models.IntegerField()
    mPG = models.IntegerField()
    additional = models.TextField(null=True,blank= True)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)
    def __unicode__(self):
        return self.model
class CarInfo(models.Model):
    vin_number = models.CharField(max_length = 17,unique = True)
    model = models.ForeignKey(CarModel)
    price = models.DecimalField(decimal_places = 2,max_digits = 10, default = 8000.00)
    dealer = models.CharField(max_length=120,null=True, blank=True)
    Red = 'Red' # Exterior
    Blue = 'Blue'       
    Black = 'Black'
    White = 'White'
    Yellow = 'Yellow'
    Siver = 'Silver'
    Green = 'Green' #Exterior Color
    Other = 'Other'
    Beige = 'Beige' # interior Color
    Brown = 'Brown' #interior Color
    Gray ='Gray'        
    INTERIOR_COLOR_CHOICES = (
        (Red,"Red"),
        (Blue,"Blue"),            
        (Black,"Black"),
        (White,"White"),
        (Beige, "Beige"),
        (Brown,"Brown"),
        (Gray,"Gray"),
        (Other,"Other"),
    )
    EXTERIOR_COLOR_CHOICES =(           
        (Black,"Black"),
        (Blue,"Blue"),
        (Green,"Green"),
        (Red,"Red"),
        (Siver,"Silver"),
        (Yellow,"Yellow"),            
        (White,"White"),            
        (Other,"Other"),            
    )
    interior_color = models.CharField(max_length=10,choices = INTERIOR_COLOR_CHOICES, default = "Black")
    exterior_color = models.CharField(max_length=10,choices = EXTERIOR_COLOR_CHOICES, default = "Black")
    mileage = models.IntegerField()
    slug = models.SlugField(unique=True,null = True, blank = True)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)    
    class Meta:
        unique_together = ('model','slug')
    def get_absolute_url(self):
        return reverse("detail",kwargs={"slug":self.slug})
    def __unicode__(self):
        return self.vin_number
# It's used to be shown in single car information
class CarImage(models.Model):    
    carinfo = models.ForeignKey(CarInfo)
    carimage = models.ImageField(upload_to = 'productions/images/')
    active = models.BooleanField(default = False)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)
    def __unicode__(self):
        return self.carinfo.vin_number
# ModelImage is for the car model which can be used to serve as the car information list images.
class ModelImage(models.Model):
    carmodel = models.ForeignKey(CarModel)
    modelimage = models.ImageField(upload_to = 'productions/images/')
    active = models.BooleanField(default = False)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)
    def __unicode__(self):
        return self.carmodel.model
    

Angel.9.10/Src/productions/views.py
from django.shortcuts import render,Http404 , render_to_response, redirect, RequestContext
from django.http import HttpResponse
from django.db import models
from .models import Product,CarModel,CarInfo
from .forms import UploadForm,ImageForm,CarImageUploadForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.forms.formsets import formset_factory
import smtplib, os
from django.conf import settings
from django import forms
from crispy_forms.helper import FormHelper
from carts.models import Cart
from django.core import serializers
# Create your views here.
def carinfo(request):
    # authentication here is used for admin change here later
    products = Product.objects.all()
    context = {"products":products}
    # "products" is used for html to call context   
    template = 'productions/carinfo.html'
    return render(request,template,context)

def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if q:
        products = CarInfo.objects.filter(model__icontains = q)
        context = {'query':q,'products':products}
        template ='productions/results.html'
    else:
        template = 'prodcutions/cars.html'
        context = {}
    return render(request,template,context)
   
def home(request):
    template = 'index.html'
    context = {"username_is":"aaaa"}
    return render(request,template,context)

def single(request,slug):   
    try:        
        product = Product.objects.get(slug=slug)         
        context = {"product":product}
        # "products" is used for html to call context       
        template = 'productions/single.html'
        return render(request,template,context)
    except:
        raise Http404
# Multiple images to upload!!!!!!!!!!!!!!!!!!!
#def upload(request):  
#    form = UploadForm(request.POST or None)    
 #   if form.is_valid():
 #       save_it = form.save(commit = False)
 #       save_it.save()
 #       return redirect("/upload/uploadsuccess/")
 #   else: 
 #       return render_to_response("productions/upload.html",locals(),context_instance = RequestContext(request))
#TODO: fixed the html
def uploadsuccess(request):
    template = 'productions/uploadsuccess.html'
    context={}
    return render(request,template,context)
def cars(request):
    doubledroplst=[]
    doubledownlst =[]
    is_have  = False
    
     #Pagination
    allproducts = CarInfo.objects.all()
    paginator = Paginator(allproducts,8)# show 5 cars in one page
    page = request.GET.get('page')
    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        cars = paginator.page(1)
    except EmptyPage:
        cars = paginator.page(paginator.num_pages)
    #end of Pagination
    
    modelinfos = CarModel.objects.all()
    for p in modelinfos:
        #print(p.make)
        for f in doubledroplst:
            if "%s"%(p.make) ==f:
                is_have = True
        if  is_have == False:
            doubledroplst.append("%s"%(p.make))
        is_have = False

    
    
    for p in modelinfos:
        doubledownlst.append(["%s"%(p.make),"%s"%(p.model)])
  #  js_data = simplejson.dumps(doubledroplst)  
   
    
   
    carmodel = CarModel.objects.filter(model__contains=allproducts.model)
    context = {"cars":cars,"carmodel":carmodel,"modelinfos":modelinfos, " doubledroplst": doubledroplst, "doubledownlst":doubledownlst}
    template = 'productions/cars.html'
    return render_to_response(template,locals(), context_instance = RequestContext(request))
# dropdownsearch only needs to pass the value of car model to find the exact car and if possible we need the time to find the used car information.
# TODO: add years to filter.
def dropdownsearch(request):
    doubledroplst=[]
    doubledownlst =[]
    is_have  = False
    
     #Pagination
    allproducts = CarInfo.objects.all()
    paginator = Paginator(allproducts,4)# show 5 cars in one page
    page = request.GET.get('page')
    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        cars = paginator.page(1)
    except EmptyPage:
        cars = paginator.page(paginator.num_pages)
    #end of Pagination
    
    modelinfos = CarModel.objects.all()
    for p in modelinfos:
        #print(p.make)
        for f in doubledroplst:
            if "%s"%(p.make) ==f:
                is_have = True
        if  is_have == False:
            doubledroplst.append("%s"%(p.make))
        is_have = False

    carmodel = CarModel.objects.filter(model__contains=allproducts.model)
    
    for p in modelinfos:
        doubledownlst.append(["%s"%(p.make),"%s"%(p.model)])
   # js_data = simplejson.dumps(doubledroplst)
    
    try:        
        q = request.GET.get('q')
        x = request.GET.get('x')
        y = request.GET.get('y')
        p = request.GET.get('p')
        priceup = request.GET.get('priceup')
        pricedown = request.GET.get('pricedown')
    except:
   
       q = None
       x = None
       y = None
       p = None
      
    if q or x or y or p:
        allcars = CarInfo.objects.all()
        modelinfos = CarModel.objects.all()
        if not x:
            x = 0
        if not y:
            y = 999999
        if not q:
            q = "a"
        if not priceup:
            priceup = 9999999999
        if not pricedown:
            pricedown = 0
        if p == "All":
            cars_m = CarInfo.objects.filter(mileage__range =  (x, y))
            cars = cars_m.filter(price__range =  (pricedown, priceup))
        elif q == "All":
            car_make = CarInfo.objects.filter(model__make__contains = p)
            cars = car_make.filter(mileage__range =  (x, y))
            cars = cars.filter(price__range =  (pricedown, priceup))
        else:  
            car_mod = CarInfo.objects.filter(model__model__contains = q)
            cars= car_mod.filter(mileage__range = (x, y))
            cars = cars.filter(price__range =  (pricedown, priceup))
        template ='productions/resultstwo.html'
        context = {"cars":cars,"carmodel":carmodel,"modelinfos":modelinfos, " doubledroplst": doubledroplst,"doubledownlst":doubledownlst}
    else:
        template = 'prodcutions/cars.html'
        context = {}
        
    return render_to_response(template,locals(),context_instance = RequestContext(request))

def Form(request):
    return render(request,"productions/form.html",{})
def imageupload(request):
    for count, x in enumerate(request.FILES.getlist("files")):
        def process(f):
            with open('prodcutions/images/' + str(count),'wb+') as destination:
                for chunk in f.chunks():
                    detination.write(chunk)
        process(x)
    return HttpResponse("File(s) uploaded!")
def detail(request,slug):
    try:        
        carinfo = CarInfo.objects.get(slug=slug)
        existed = False
        context = {"carinfo":carinfo,"existed":existed}
        # "products" is used for html to call context       
        template = 'productions/detail.html'
        return render(request,template,context)
    except:
        raise Http404        
def upload(request):
   # if not request.user.is_authenticated():
    #    return redirect ("login/")
    form = UploadForm(request.POST or None)
  
    if form.is_valid():
        server = smtplib.SMTP('smtp.gmail.com:587')
        server.ehlo()
        server.starttls()
        vin_number = form.cleaned_data.get("vin_number")
        model = form.cleaned_data.get("model")
        mileage = form.cleaned_data.get("mileage")
        last_name = form.cleaned_data.get("last_name")
        first_name = form.cleaned_data.get("first_name")
        address = form.cleaned_data.get("address")
        phone_number=form.cleaned_data.get("phone_number")        
        YourEmail = "duancwd@gmail.com"
        subject = 'ANGEL TECH AUTO SERVICES'
        from_email = settings.EMAIL_HOST_USER      
        to_email  = [settings.EMAIL_HOST_USER,YourEmail]
        contact_message = "Dear Mr  model: !!" 
        send_mail(subject,
                 contact_message,
                 from_email,
                 to_email,
                 fail_silently = True,)      
            
        save_it = form.save(commit = False)        
        save_it.save()
        return redirect("/upload/uploadsuccess/")
    else:
        return render_to_response("productions/upload.html",locals(),context_instance = RequestContext(request))
def contact(request):
    template = 'contact.html'
    context={}
    return render(request,template,locals())

Angel.9.10/Src/templates/productions/carinfo.html
<!DOCTYPE HTML>
<html>
<head>
<title>Angel Tech</title>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href={% static "css/style.css" %} rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet"  href={% static "css/style3.css" %} /> 
<link rel="stylesheet" href={% static "css/magnific-popup.css" %} /> 
<!-- start js -->

	
<!-- start top_js_button -->
    <style>
	#tfheader{
		background-color:#c3dfef;
	}
	#tfnewsearch{
		float:right;
		padding:20px;
	}
	.tftextinput{
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		border:1px solid #0076a3; border-right:0px;
		border-top-left-radius: 5px 5px;
		border-bottom-left-radius: 5px 5px;
	}
	.tfbutton {
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		outline: none;
		cursor: pointer;
		text-align: center;
		text-decoration: none;
		color: #ffffff;
		border: solid 1px #0076a3; border-right:0px;
		background: #0095cd;
		background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
		background: -moz-linear-gradient(top,  #00adee,  #0078a5);
		border-top-right-radius: 5px 5px;
		border-bottom-right-radius: 5px 5px;
	}
	.tfbutton:hover {
		text-decoration: none;
		background: #007ead;
		background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
		background: -moz-linear-gradient(top,  #0095cc,  #00678e);
	}
	/* Fixes submit button height problem in Firefox */
	.tfbutton::-moz-focus-inner {
	  border: 0;
	}
	.tfclear{
		clear:both;
	}
</style>
</head>
<body>
<!-- start header --><!-- start slider -->
<div class="slider_bg">
<div class="wrap">
	<div class="slider" id="home"></div>
</div>
</div>
<!-- start main --><!-- start work-page -->
<div class="work_bg">
<div class="wrap">
	<div class="work" id="work">
		<div class="main_text1">
			<h2>Angel Tech</h2>
		</div>		
		<!-- start grids_of_2 -->
		<div class="grids_of_2">
				<div id="tfheader">
					<form id="tfnewsearch" role="search" action="/carinfo/s/">
							<input type="text" class="tftextinput" name="q" placeholder="Input Keyword To Get What You want." size="35" maxlength="120">
							<input type="submit" value="search" class="tfbutton">
					</form>
					
				</div>

	{% for product in products %}
	
		<div class="grid_1_of_2">
		{% for item in product.productimage_set.all %}
		{% if item.featured %} 
				<div class="grid_pic">
					<a href='{% url "single_product" product.slug%}'><img src="{{MEDIA_URL}}{{ item.image }}" height="200" width="200" /></a>
				</div>
		{% endif %}
		{% endfor %}
				<div class="grid_text">
					<a href='{{product.get_absolute_url}}'/><h2>{{product.carName}}</h2></a>
					 <li>Price: {{product.price}}$</li>
					 <li> Exterior Color: {{product.exteriorColor}}</li>
					 <li> Interior Color : {{product.interiorColor}}</li>
					 <li> Mileage : {{product.mileage}} miles</li>
				</div>
			</div>
	{% endfor %}
		</div>	
		
			
			<div class="clear"></div>
		</div>	
		<!-- end grids_of_2 -->
		<div class="wrk_btn"> <a class="popup-with-zoom-anim" href={% url "home"%}>HomePage</a></div>
		<!---start-mfp ---->	
	  <div id="small-dialog" class="mfp-hide">
			
				</div>
			</div>
			<!---end-mfp ---->	
	</div>
</div>
</div>
<!-- start service-page --><!-- start contact-page -->
<div class="footer_bg">
  <div class="wrap">
    <div class="wrapper">
      <div class="footer">
        <div class="clear">Address 88888888 TEL 8888888888   CopyRight bulabulabula</div>
	</div>
</div>
</div>
</div>
<div style="display:none"></div>
</body>
</html>

Angel.9.10/Src/templates/productions/form.html
<form method="Post" action="../imageupload/" enctype="multipart/form-data">{% csrf_token%}
    <input type="file" name = "files" multiple />
    <input type = "submit" value="Upload" />
</form>

Angel.9.10/Src/templates/productions/results.html
<!DOCTYPE HTML>
<html>
<head>
<title>Angel Tech</title>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href={% static "css/style.css" %} rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet"  href={% static "css/style3.css" %} /> 
<link rel="stylesheet" href={% static "css/magnific-popup.css" %} /> 
<!-- start js -->

	
<!-- start top_js_button -->
    <style>
	#tfheader{
		background-color:#c3dfef;
	}
	#tfnewsearch{
		float:right;
		padding:20px;
	}
	.tftextinput{
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		border:1px solid #0076a3; border-right:0px;
		border-top-left-radius: 5px 5px;
		border-bottom-left-radius: 5px 5px;
	}
	.tfbutton {
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		outline: none;
		cursor: pointer;
		text-align: center;
		text-decoration: none;
		color: #ffffff;
		border: solid 1px #0076a3; border-right:0px;
		background: #0095cd;
		background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
		background: -moz-linear-gradient(top,  #00adee,  #0078a5);
		border-top-right-radius: 5px 5px;
		border-bottom-right-radius: 5px 5px;
	}
	.tfbutton:hover {
		text-decoration: none;
		background: #007ead;
		background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
		background: -moz-linear-gradient(top,  #0095cc,  #00678e);
	}
	/* Fixes submit button height problem in Firefox */
	.tfbutton::-moz-focus-inner {
	  border: 0;
	}
	.tfclear{
		clear:both;
	}
</style>
</head>
<body>
<!-- start header --><!-- start slider -->
<div class="slider_bg">
<div class="wrap">
	<div class="slider" id="home"></div>
</div>
</div>
<!-- start main --><!-- start work-page -->
<div class="work_bg">
<div class="wrap">
	<div class="work" id="work">
		<div class="main_text1">
			<h2>Angel Tech</h2>
		</div>		
		<!-- start grids_of_2 -->
		<div class="grids_of_2">
				<div id="tfheader">
					<form id="tfnewsearch" role="search" action="/carinfo/s/">
							<input type="text" class="tftextinput" name="q" placeholder="Input Keyword To Get What You want." size="35" maxlength="120">
							<input type="submit" value="search" class="tfbutton">
					</form>
					
				</div>

	{% for product in products %}
	
		<div class="grid_1_of_2">
		{% for item in product.productimage_set.all %}
		{% if item.featured %} 
				<div class="grid_pic">
					<a href='{% url "single_product" product.slug%}'><img src="{{MEDIA_URL}}{{ item.image }}" height="200" width="200" /></a>
				</div>
		{% endif %}
		{% endfor %}
				<div class="grid_text">
					<a href='{{product.get_absolute_url}}'/><h2>{{product.carName}}</h2></a>
					 <li>Price: {{product.price}}$</li>
					 <li> Exterior Color: {{product.exteriorColor}}</li>
					 <li> Interior Color : {{product.interiorColor}}</li>
					 <li> Mileage : {{product.mileage}} miles</li>
				</div>
			</div>
	{% endfor %}
		</div>	
		
			
			<div class="clear"></div>
		</div>	
		<!-- end grids_of_2 -->
		<div class="wrk_btn"> <a class="popup-with-zoom-anim" href={% url "carinfo"%}>Back</a></div>
		<!---start-mfp ---->	
	  <div id="small-dialog" class="mfp-hide">
			
				</div>
			</div>
			<!---end-mfp ---->	
	</div>
</div>
</div>
<!-- start service-page --><!-- start contact-page -->
<div class="footer_bg">
  <div class="wrap">
    <div class="wrapper">
      <div class="footer">
        <div class="clear">Address 88888888 TEL 8888888888   CopyRight bulabulabula</div>
	</div>
</div>
</div>
</div>
<div style="display:none"></div>
</body>
</html>

Angel.9.10/Src/templates/productions/single.html
{% extends "banner.html" %}
{% block content %}
<div>
    <h1><font color="Black">{{product.carName}}</font></h1>
    <div>
    {% for item in product.productimage_set.all %}
    
     <img src = "{{MEDIA_URL}}{{ item.image }}" height="200" width="200"/></a>       
    
    {% endfor %}
    <form class="navbar-form navbar-right" action='{% url "checkout"%}'>
        <button type="submit" class="btn btn-success">Checkout</button>				
    </form>
    <form class="navbar-form navbar-right" action='{% url "carinfo"%}'>
        <button type="submit" class="btn btn-success">Back</button>				
    </form>
    </div>
    <div>
        <font color="blue">
        <li> Price: {{product.price}}$</li>
        <li> Exterior Color: {{product.exteriorColor}}</li>
        <li> Interior Color : {{product.interiorColor}}</li>
        <li> Mileage : {{product.mileage}} miles</li>
        <li> Transmission: {{product.transmission}}$</li>
        <li> Engine: {{product.Engine}}</li>
        <li> Major Options : {{product.MajorOptions}}</li>
        
        </font>
    </div>
</div>
{% endblock%}